global:
  scrape_interval: 15s

scrape_configs:
  # Coleta métricas dos serviços Fastify (cart, payment, notification)
  - job_name: 'node-services'
    static_configs:
      - targets:
        - 'cart-service:9100'
        - 'payment-service:9100'
        - 'notification-service:9100'

  # Coleta métricas dos serviços Lumen/PHP (gateway, user, product, order)
  - job_name: 'php-services'
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'api-gateway:80'
        - 'user-service:80'
        - 'product-service:80'
        - 'order-service:80'

  # Coleta métricas do RabbitMQ
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']
    basic_auth:
      username: 'root'
      password: 'root'